CR-3115: excluded merge from hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -11,20 +11,16 @@ merging=$(git rev-parse -q --verify MERGE_HEAD)
 
 if [[ -z $merging ]]; then
 
-    pylintexists=$(which pylint)
+    pylint --help > /dev/null || { echo "\033[0;33m Pylint not found\033[0m"; exit 0; }
 
-    if [[ ! $pylintexists =~ "not found" ]]; then
+    fileList=$(git diff --diff-filter=d --cached --name-only)
+    pyFileList=$(echo "$fileList" | grep -E '\.(py)$')
 
-        fileList=$(git diff --diff-filter=d --cached --name-only)
-        pyFileList=$(echo "$fileList" | grep -E '\.(py)$')
-
-        if [ ${#pyFileList} -gt 0 ]; then
-            if ! pylint ${pyFileList[*]} ; then
-                echo "\033[0;33m Pylint failed! \033[0m"
-                exit 1
-            fi
+    if [ ${#pyFileList} -gt 0 ]; then
+        if ! pylint ${pyFileList[*]} ; then
+            echo "\033[0;33m Pylint failed! \033[0m"
+            exit 1
         fi
-    else 
-        echo "\033[0;33m Pylint not found\033[0m"
     fi
+
 fi
